MAX_FILE_LINES = 40000
INPUT_PATH = 'data/ResalePricesSingapore.csv'
DISK_FOLDER = 'processed'
OUTPUT_FOLDER = 'output'


STATISTIC_TYPE = {
    1: 'MIN_AREA', 2: 'AVG_AREA', 3: 'STD_AREA', 4: 'MIN_PRICE', 5: 'AVG_PRICE', 6: 'STD_PRICE'
}

TOWN_MAPPING = {
    'ANG MO KIO': 0,
    'BEDOK': 1,
    'BUKIT BATOK': 2,
    'CLEMENTI': 3,
    'CHOA CHU KANG': 4,
    'HOUGANG': 5,
    'JURONG WEST': 6,
    'PUNGGOL': 7,
    'WOODLANDS': 8,
    'YISHUN': 9
}

# TOWNS = ['ANG MO KIO', 'BEDOK', 'BISHAN', 'BUKIT BATOK', 'BUKIT MERAH',
#          'BUKIT PANJANG', 'BUKIT TIMAH', 'CENTRAL AREA', 'CHOA CHU KANG',
#          'CLEMENTI', 'GEYLANG', 'HOUGANG', 'JURONG EAST', 'JURONG WEST',
#          'KALLANG/WHAMPOA', 'MARINE PARADE', 'PASIR RIS', 'PUNGGOL',
#          'QUEENSTOWN', 'SEMBAWANG', 'SENGKANG', 'SERANGOON', 'TAMPINES',
#          'TOA PAYOH', 'WOODLANDS', 'YISHUN']

# TOWN_MAPPING = {town: i for i, town in enumerate(TOWNS)}
